language: c
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

install:
  pip install --user -q cython

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make all
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
  - cd ..
  - python setup.py test
